# Generated by Django 3.2.14 on 2022-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('depreciation', models.CharField(db_column='Depreciation', max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
    ]
