# Generated by Django 3.2.14 on 2022-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedAsset',
            fields=[
                ('chanded_asst_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset', models.CharField(db_column='Asset', max_length=50)),
            ],
            options={
                'db_table': 'changed_asset',
                'managed': False,
            },
        ),
    ]
